// <auto-generated />
namespace ForumDImage.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class imageDisplayName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageDisplayName));
        
        string IMigrationMetadata.Id
        {
            get { return "201505260223575_imageDisplayName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
